default:
    image: "ubuntu:latest"

stages:
  - getinfo
  - build

getinfo:
    stage: getinfo

    script:
      - apt-get install -y bash
      - source ./buildconfig.sh
      - echo "PACKAGE_NAME=$package" >> build.env

    artifacts:
      reports:
        dotenv: build.env

build-job:
    stage: build
    cache:
      - key:    "Makefile"
        paths:  ["build/deps"]

    script:
      - apt-get install -y curl zip tar gzip bash bzip2 make
      - make

    artifacts:
      - build/dist/$PACKAGE_NAME/latest/

    dependencies:
      - build
