default:
    image: "ubuntu:latest"

stages:
  - getinfo
  - lockfile
  - build

getinfo:
    stage: getinfo

    script:
      - apt-get install -y bash
      - source ./buildconfig.sh
      - echo "VERSION=$version" >> build.env
      - echo "PACKAGE=$package" >> build.env
      - echo "BUILD_NUM=$build" >> build.env
      - echo "NAME=$name" >> build.env
      - echo "DEBUG=$debug" >> build.env

    artifacts:
      reports:
        dotenv: build.env

lockfile:
    stage: lockfile
    cache:
      - key:
            files:
              - Makefile
        paths:  ["build/deps"]

    script:
        - make generate-deps-lockfile

    artifacts:
        name: "Dependency lockfile"

build-job:
    stage: build

    cache:
      - key:
            files:
              - deps.lock
        paths:  ["build/deps"]

    script:
      - dpkg --add-architecture i386
      - apt-get update
      - apt-get install -y curl zip bzip2 make file libc6:i386
      - make

    artifacts:
      name: "$PACKAGE-$VERSION-b$BUILD_NUM"
      paths:
        - build/dist/$PACKAGE/latest/

    dependencies:
      - getinfo
      - lockfile
