default:
    image: alpine:3.14

stages:
-   sast
-   build

build-job:
    stage: build
    cache:
    -   key:    "Makefile"
        paths:  ["build/deps"]

    script:
    -   apk add --no-cache curl zip tar gzip bash bz2
    -   make

sast:
    stage: sast

include:
-   template: Security/SAST.gitlab-ci.yml

