name: MushMatch Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build MushMatch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install zip bzip2 gzip tar curl bash

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4

    - name: Install Mustache (build dependency)
      run: |
        sudo go install github.com/cbroglie/mustache/cmd/mustache@latest
        which mustache

    - name: Cache Build Environment Downloads
      id: cache-downloads
      uses: actions/cache@v2
      with:
        path: |
          build
          !build/ut-server
        key: ${{ runner.os }}-${{ hashFiles('build/deps/**') }}
        restore-keys: |
            ${{ runner.os }}-

    - name: Download Build Environment
      if: steps.cache-downloads.outputs.cache-hit != 'true'
      run: make download

    - name: Setup Build Environment
      run: make configure

    - name: Build
      run: make build

    - uses: actions/upload-artifact@v2
      with:
        name: mushmatch-distrib
        path: build/ut-server/Dist/Latest/*
        if-no-files-found: error
