name: MushMatch Makefile build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build MushMatch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install zip bzip2 gzip tar curl bash

    - name: Setup Go
      uses: actions/setup-go@v2.1.4

    - name: Install Mustache (build dependency)
      run: go get github.com/cbroglie/mustache/...

    - name: Add Go bin to PATH
      run: echo 'export PATH="$HOME/go/bin:$PATH"'>>~/.bash_profile

    - name: Check Mustache is installed
      run: |
        echo $PATH
        which mustache

    - name: Cache build environment downloads
      id: cache-downloads
      uses: actions/cache@v2
      with:
        path: |
          build
          !build/ut-server
        key: ${{ runner.os }}-${{ hashFiles('build/deps/**') }}
        restore-keys: |
            ${{ runner.os }}-

    - name: Download build environment
      if: steps.cache-downloads.outputs.cache-hit != 'true'
      run: make download

    - name: Set up build environment
      run: make configure

    - name: Build
      run: make build

    - uses: actions/upload-artifact@v2
      name: Upload build artifacts
      with:
        name: mushmatch-distrib
        path: build/ut-server/Dist/Latest/*
        if-no-files-found: error
